repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
        name: "end-of-file-fixer"
    -   id: trailing-whitespace
        name: "trailing-whitespace"
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.7
  hooks:
      - id: ruff-check
        name: "ruff-import-order"
        args: [ "--select", "I", "--fix" ]
        exclude: ^build/
      - id: ruff-check
        name: "ruff-check"
        args: [ "--fix" ]
        exclude: ^build/
      - id: ruff-format
        name: "ruff-format"
        exclude: ^build/
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
    -   id: prettier
        files: \.(css|html|js)$
        exclude: (\.min\.js|\.min\.css|templates/index_bootstrap\.html)
-   repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.11.0
    hooks:
    -   id: shellcheck
-   repo: https://github.com/hadolint/hadolint
    rev: v2.13.1-beta # Use the latest stable version
    hooks:
    -   id: hadolint
-   repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
    -   id: yamllint
-   repo: https://github.com/rhysd/actionlint
    rev: v1.7.7 # Use the latest stable version
    hooks:
    -   id: actionlint
-   repo: https://github.com/pappasam/toml-sort
    rev: v0.24.2
    hooks:
    -   id: toml-sort-fix
-   repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.404
    hooks:
    -   id: pyright
