# WARNING: NEVER use 'docker-compose down -v' as it removes ALL volumes including production data!
# For E2E tests, use: BIRDNET_DATA_VOLUME=birdnet-test-data docker-compose up/down
# To remove test volume only: docker volume rm birdnet-test-data
services:
  # Init container to ensure assets are installed
  birdnet-pi-init:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: birdnet-pi-init
    environment:
      BIRDNET_ASSETS_VERSION: ${BIRDNET_ASSETS_VERSION:-v2.1.0}
    command: >
      sh -c "
      echo 'Checking and installing BirdNET assets if needed...' &&
      uv run install-assets install $${BIRDNET_ASSETS_VERSION} --skip-existing &&
      echo 'Assets ready!' &&
      echo 'Ensuring config file exists...' &&
      if [ ! -f /var/lib/birdnetpi/config/birdnetpi.yaml ]; then
        echo 'Copying config template to volume...' &&
        mkdir -p /var/lib/birdnetpi/config &&
        cp /opt/birdnetpi/config_templates/birdnetpi.yaml /var/lib/birdnetpi/config/birdnetpi.yaml &&
        echo 'Config template copied.';
      else
        echo 'Config file already exists.';
      fi
      "
    volumes:
      - ${BIRDNET_DATA_VOLUME:-birdnet-data}:/var/lib/birdnetpi # Shared data volume
    networks:
      - birdnetpi-network

  birdnet-pi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: birdnet-pi
    restart: unless-stopped
    depends_on:
      birdnet-pi-init:
        condition: service_completed_successfully
    environment:
      PULSE_SERVER: host.docker.internal
      DOCKER_CONTAINER: "true"
      BIRDNET_ASSETS_VERSION: ${BIRDNET_ASSETS_VERSION:-v2.1.0}
    ports:
      - "8000:8000"   # Caddy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 5s
      timeout: 10s
      retries: 5
    command: /usr/bin/supervisord -c /etc/supervisor/supervisord.conf -u birdnetpi
    volumes:
      - ${BIRDNET_DATA_VOLUME:-birdnet-data}:/var/lib/birdnetpi # Persistent data storage
      - ~/.config/pulse:/home/birdnetpi/.config/pulse
    networks:
      - birdnetpi-network

volumes:
  birdnet-data:
    driver: local
  birdnet-test-data:
    driver: local

networks:
  birdnetpi-network:
    driver: bridge
