services:
  birdnet-pi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: birdnet-pi
    restart: unless-stopped
    ports:
      - "8000:8000"   # Caddy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 5s
      timeout: 10s
      retries: 5
    privileged: true
    volumes:
      - birdnet-data:/mnt/birdnet # Persistent data storage
      - /dev/snd:/dev/snd # Expose host audio devices
    networks:
      - birdnetpi-network

volumes:
  birdnet-data:
    driver: local

networks:
  birdnetpi-network:
    external: true
