# WARNING: NEVER use 'docker-compose down -v' as it removes ALL volumes including production data!
# For E2E tests, use: BIRDNET_DATA_VOLUME=birdnet-test-data docker-compose up/down
# To remove test volume only: docker volume rm birdnet-test-data
#
# PERSISTENCE MODEL:
# - Config and data are stored in Docker volume (birdnet-data) for persistence
# - Init container ensures proper permissions and initial config setup
# - User modifications to config are preserved across container restarts
# - Home Assistant users: config persists in volume, survives container updates
#
services:
  # Init container to ensure assets are installed
  birdnet-pi-init:
    build:
      context: .
      dockerfile: Dockerfile
      target: init  # Use the init stage which runs as root
    container_name: birdnet-pi-init
    environment:
      BIRDNET_ASSETS_VERSION: ${BIRDNET_ASSETS_VERSION:-v2.1.1}
    logging:
      driver: json-file
    volumes:
      - ${BIRDNET_DATA_VOLUME:-birdnet-data}:/var/lib/birdnetpi # Shared data volume
    networks:
      - birdnetpi-network

  birdnet-pi:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime  # Use the runtime stage, not init
    container_name: birdnet-pi
    restart: unless-stopped
    depends_on:
      birdnet-pi-init:
        condition: service_completed_successfully
    environment:
      PULSE_SERVER: host.docker.internal:4713
      DOCKER_CONTAINER: "true"
      BIRDNET_ASSETS_VERSION: ${BIRDNET_ASSETS_VERSION:-v2.1.1}
      # Force PortAudio to use PulseAudio backend instead of ALSA
      PA_ALSA_PLUGHW: 0
    ports:
      - "8000:8000"   # Caddy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    logging:
      driver: json-file
    command: /usr/bin/supervisord -c /etc/supervisor/supervisord.conf -u birdnetpi
    volumes:
      - ${BIRDNET_DATA_VOLUME:-birdnet-data}:/var/lib/birdnetpi # Persistent data storage
      - ~/.config/pulse/cookie:/home/birdnetpi/.config/pulse/cookie:ro # PulseAudio auth cookie only (read-only)
      - ./src:/opt/birdnetpi/src:ro # Source code bind mount for development
    networks:
      - birdnetpi-network

volumes:
  birdnet-data:
    driver: local
  birdnet-test-data:
    driver: local

networks:
  birdnetpi-network:
    driver: bridge
