services:
  birdnet-pi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: birdnet-pi
    restart: unless-stopped
    environment:
      PULSE_SERVER: host.docker.internal
      DOCKER_CONTAINER: "true"
    ports:
      - "8000:8000"   # Caddy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 5s
      timeout: 10s
      retries: 5
    command: /usr/bin/supervisord -c /etc/supervisor/supervisord.conf -u birdnetpi
    volumes:
      - birdnet-data:/var/lib/birdnetpi # Persistent data storage
      - ~/.config/pulse:/home/birdnetpi/.config/pulse
    networks:
      - birdnetpi-network

volumes:
  birdnet-data:
    driver: local

networks:
  birdnetpi-network:
    driver: bridge
