name: 'Setup uv'
description: 'Installs uv and adds it to the PATH'

runs:
  using: 'composite'
  steps:
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "${HOME}/.local/bin" >> "${GITHUB_PATH}"
      shell: bash
